[project]
name = "locally-tilted-sampler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flax>=0.12.0",
    "jax>=0.8.0",
    "jaxtyping>=0.3.3",
    "optax>=0.2.0",
]
