defaults:
  - _self_
  - /hydra: ignore_log
  - override hydra/job_logging: disabled  

seed: 80801

target:
  input_dim: 2
  gmm_n_mixes: 40
base:
  initial_sigma: 20

model:
  hidden_dim: 256 # Hidden dimension size of the MLP.
  depth: 3 # Number of layers in the MLP.

optimiser:
  name: adam
  learning_rate: 0.001

training:
  num_epochs: 100
  batches_per_epoch: 50
  batch_size: 64
  timesteps_for_loss: 10
  num_timesteps: 100

sampling:
  num_timesteps: {training.num_timesteps}