defaults:
  - _self_
  - /hydra: ignore_log
  - override hydra/job_logging: disabled  

seed: 80801

target:
  input_dim: 2
  gmm_n_mixes: 40
base:
  initial_sigma: 20

model:
  hidden_dim: 256 # Hidden dimension size of the MLP.
  depth: 3 # Number of layers in the MLP.

optimiser:
  name: adam
  learning_rate: 0.001

training:
  num_epochs: 5000
  batches_per_epoch: 100
  batch_size: 128
  timesteps_for_loss: 32
  num_timesteps: 200

sampling:
  num_timesteps: ${training.num_timesteps}

wandb:
  project: Locally-Tilted-Sampler
  name: GMM40